---
engines:
  eslint:
    enabled: true
    config:
      extensions:
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 60

ratings:
  paths:
  - app/**.js
exclude_paths:
- "test/"
- "docs/"
- "devtools/"
- "coverage/"
- "node_modules/"
- "build/"
- "migrations"
- "app/inventory/routers/"
- "app/core/routers/"
- "app/identity/routers/"
- "app/adminer/routers/"
- "app/reports/routers/"
- "app/analytics/routers/"
- "app/orchestration/routers/"
- "app/config/routers/"
- "app/inventory/entities/"
- "app/core/entities/"
- "app/identity/entities/"
- "app/adminer/entities/"
- "app/reports/entities/"
- "app/analytics/entities/"
- "app/orchestration/entities/"
- "app/config/entities/"
