---
engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 60

ratings:
  paths:
  - app/**.js
exclude_paths:
- "test/"
- "node_modules/"
- "build/"
- "migrations"
- "app/inventory/routers/"
- "app/core/routers/"
- "app/identity/routers/"
- "app/adminer/routers/"
- "app/reports/routers/"
- "app/playbooks/routers/"
- "app/orchestration/routers/"
- "app/config/routers/"
