language: node_js
node_js:
  - '6'
  - '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
addons:
  code_climate:
    repo_token: 6cf035555359edcee27f4766f7d37e232c224140630c0af05322fa09e8d0603a
env:
  - CXX=g++-5 DB=mongodb NODE_ENV=test
cache:
  directories:
    - node_modules
services:
  - mongodb
before_install:
  - npm install -g node-gyp istanbul
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:1025 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
script:
  - npm run coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage -p .
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter

webhooks:
  urls:
    - https://webhooks.gitter.im/e/38046855b88e43009941
  on_success: change
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
