language: node_js
node_js:
  - '6'
  - '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
env:
  - CXX=g++-5 DB=mongodb NODE_ENV=test
cache:
  directories:
    - node_modules
services:
  - mongodb
before_install:
  - npm install -g node-gyp gulp
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:1025 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
